### PR TITLE
fix: stop all services first to update the service status in the service registration during a `kurtosis enclave stop` execution

### LINKED ISSUE #1711: The stop enclave CLI command is not updating the service status in the service registration repository
### What's your CLI version?

0.85.1

### Description & steps to reproduce

The `kurtosis enclave stop {enclave-identifier}` kill all the container in the Docker backend but this workflow doesn't unregister the user services in the user service registration repository

### Desired behavior

It should update the service status to "stop" in the service registration repository because otherwise we will have conflicts if we want to restart the services

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### What area of the product does this pertain to?

CLI: the Command Line Interface

### PR DESCRIPTION
**Pull request by leoporoli**
## Description:
unregister the enclave services during a `kurtosis enclave stop` execution

## Is this change user-facing?
NO

## References (if applicable):
Fix #1711

### CODE REVIEW

**Review by h4ck3rk3y — APPROVED** [review]
sounds alright - this puts the logic inside the CLI though; is there a world where we change `StopEnclave` inside engine to stop services first instead?

that way typescript/curl etc get it for free

File: cli/cli/commands/enclave/stop/stop.go [hunk 1]
```diff
@@ -4,11 +4,13 @@ import (
 	"context"
 	"fmt"
 	"github.com/kurtosis-tech/kurtosis/api/golang/engine/kurtosis_engine_rpc_api_bindings"
+	"github.com/kurtosis-tech/kurtosis/api/golang/engine/lib/kurtosis_context"
```
Comment (h4ck3rk3y) [inline cli/cli/commands/enclave/stop/stop.go:7]: leaving a comment here for discussion to prevent auto merge

wonder whether StopEnclave inside Engine Server can do a service stop so that ts/curl/any other frontend gets this functionality for free

Comment (leoporoli) [reply cli/cli/commands/enclave/stop/stop.go:7]: As we talked in Slack the problem is that there is not connection between the Engine and the APIC server, so doesn't allow us to do it in the engine side
