### PR TITLE
fix: print enclave names even after restart during clean

### LINKED ISSUE #133: [bug]: `kurtosis clean -a` only prints the name of *some* enclaves, not all.
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.68.5

### (Optional) What is your metrics user ID?

07d14724970e58810d93e5520436603ca4c113ad9bd608bec371f9122534cf4b

### What is the severity of this bug?

Papercut, this bug is frustrating, but I have a workaround.

### Description & steps to reproduce

When I have many enclaves and run `kurtosis clean -a`, I see that Kurtosis removes both running and stopped enclaves and prints out their UUID and name. However, I noticed that not all of the enclave names got printed (even though the removed enclave UUIDs got printed). See screenshots below.

I had many running enclaves:
Screenshot 2023-03-09 at 4 26 27 PM

But when I ran `kurtosis clean -a`, it only printed the names of _some_ of the enclaves that were removed:
Screenshot 2023-03-09 at 4 26 51 PM

### Relevant log output

See screenshots above.

### Desired behavior

I would expect that everytime I run `kurtosis clean -a`, both the UUID and name of all removed enclaves will get printed for me.

### PR DESCRIPTION
**Pull request by h4ck3rk3y**

### CODE REVIEW

**Comment by h4ck3rk3y** [comment]
https://user-images.githubusercontent.com/6670312/224962866-e14a3fc6-5b3c-407c-839d-f9516252d3d6.mov

File: engine/server/engine/enclave_manager/enclave_manager.go [hunk 1]
```diff
@@ -305,14 +313,19 @@ func (manager *EnclaveManager) Clean(ctx context.Context, shouldCleanAll bool) (
 	if len(successfullyRemovedArtifactIds) > 0 {
 		logrus.Infof("Successfully removed the enclaves")
 		sort.Strings(successfullyRemovedArtifactIds)
-		for _, successfullyRemovedEnclaveUuid := range successfullyRemovedArtifactIds {
-			enclaveName := manager.getEnclaveNameForEnclaveUuidUnlocked(successfullyRemovedEnclaveUuid)
+		for _, successfullyRemovedEnclaveUuidStr := range successfullyRemovedArtifactIds {
```
Comment (gbouv) [inline engine/server/engine/enclave_manager/enclave_manager.go]: Is `successfullyRemoved_Artifact_Ids ` expected here? isn't this about enclaves? 
Also, `successfullyRemovedEnclave_Uuid_Str` seem to be UUID, so maybe also rename this to xxxUUID instead

**Review by gbouv — APPROVED** [review]
