### PR TITLE
fix: return the correct yaml parsing error

### LINKED ISSUE #1690: Running an enclave from a YAML file that is invalid (spacing in indent) has cryptic error
### What's your CLI version?

0.85.3

### Description & steps to reproduce

Reproduce:

Run the ethereum-package with `kurtosis run github.com/kurtosis-tech/ethereum-package --args-file /tmp/args-file.yml` with the following yaml:

```
participants:
  - el_client_type: geth
    el_client_image: 'ethereum/client-go:alltools-v1.13.4'
    cl_client_type: lighthouse
    cl_client_image: 'sigp/lighthouse:deneb'
mev_type: full
mev_params:
	mev_builder_cl_image: 'sigp/lighthouse:deneb'
additional_services: []
```

notice the indentation on `mev_builder_cl_image` is too many spaces.

Kurtosis will return the following error:

```
➜  kurtosis-tech kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package --args-file /tmp/etherem-package-arg-file.yml
panic: Propagate must be provided with a cause

goroutine 1 [running]:
github.com/kurtosis-tech/stacktrace.Propagate(...)
	/go/pkg/mod/github.com/kurtosis-tech/stacktrace@v0.0.0-20211028211901-1c67a77b5409/stacktrace.go:85
github.com/kurtosis-tech/kurtosis/cli/cli/commands/run.getArgsFromFilepathOrURL({0x3079746a8, 0x21})
	/root/project/cli/cli/commands/run/run.go:741 +0x6f2
github.com/kurtosis-tech/kurtosis/cli/cli/commands/run.run({0x101f72320, 0xc0001b2ab0}, {0x101f8ac38, 0xc000514e80}, {0xc0001e2820?, 0xc000620148?}, {0x101f79038?, 0xc000065540}, 0x1015eacc5?, 0xc00041ce30)
	/root/project/cli/cli/commands/run/run.go:314 +0x4d4
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command.(*EngineConsumingKurtosisCommand).getRunFunc.func1({0x101f72320, 0xc0001b2ab0}, 0x0?, 0xc000064be0?)
	/root/project/cli/cli/command_framework/highlevel/engine_consuming_kurtosis_command/engine_consuming_kurtosis_command.go:247 +0x224
github.com/kurtosis-tech/kurtosis/cli/cli/command_framework/lowlevel.(*LowlevelKurtosisCommand).MustGetCobraCommand.func2(0xc00062ac00?, {0xc000064be0, 0x1, 0x5})
	/root/project/cli/cli/command_framework/lowlevel/lowlevel_kurtosis_command.go:300 +0x44e
github.com/spf13/cobra.(*Command).execute(0xc00062ac00, {0xc000064b90, 0x5, 0x5})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x102f85100)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/root/project/cli/cli/main.go:52 +0x7d
```

### Desired behavior

A clean error telling me that the yaml file I used as an input had a validation error. Even better - tell me which part is invalid

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

CLI: the Command Line Interface

### PR DESCRIPTION
**Pull request by tedim52**
## Description:
Fixes https://github.com/kurtosis-tech/kurtosis/issues/1690

## Is this change user facing?
YES

### CODE REVIEW

**Review by galenmarchetti — APPROVED** [review]

File: cli/cli/commands/run/run.go [hunk 1]
```diff
@@ -738,7 +738,7 @@ func getArgsFromFilepathOrURL(packageArgsFile string) (string, error) {
 
 	packageArgsFileStr := string(packageArgsFileBytes)
 	if packageArgParsingErr := validateSerializedArgs(packageArgsFileStr); packageArgParsingErr != nil {
-		return "", stacktrace.Propagate(err, "attempted to validate '%v' but failed", packageArgsFileFlagKey)
+		return "", stacktrace.Propagate(packageArgParsingErr, "attempted to validate '%v' but failed", packageArgsFileFlagKey)
```
Comment (h4ck3rk3y) [inline cli/cli/commands/run/run.go:741]: this must have been panic-ing
