### PR TITLE
fix: show container status instead of service status in enclave inspect

### LINKED ISSUE #1351: CLI enclave inspect displays incorrect service status
### What's your CLI version?

0.82.24

### Description & steps to reproduce

`kurtosis enclave inspect delicate-circle`
```
Name:           delicate-circle
UUID:            d4714e488001
Status:          RUNNING
Creation Time:   Thu, 14 Sep 2023 23:02:27 EDT

========================================= Files Artifacts =========================================
UUID           Name
6794261e33a0   config_file

========================================== User Services ==========================================
UUID           Name        Ports    Status
d3e6e5d6d2ef   relayer     <none>   RUNNING
e124c43d46b0   validator   <none>   RUNNING
e124c43d46b0   validator   <none>   RUNNING
```

Even though docker reports these services have exited.
```
0b59b4d7e02b   gcr.io/abacus-labs-dev/hyperlane-agent:9612623-20230829-154513   "/bin/sh -c ./relayer"   4 days ago    Exited (1) 4 days ago                                                                relayer--d3e6e5d6d2ef4724abfc82d231b0e137
1314f28abd3d   gcr.io/abacus-labs-dev/hyperlane-agent:9612623-20230829-154513   "/bin/sh -c ./valida…"   4 days ago    Exited (1) 27 hours ago
```

### Desired behavior

enclave inspect should report these services are `STOPPED` not `RUNNING`.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
## Description:
If a service eventually dies we would still show `RUNNING` while in reality it would be stopped

1. Create an enclave
2. Stop a service
3. Use inspect -> this prints service status Running (Kurtosis was told to keep it running)

Post this PR

3. This would print container status -> Stopped - actually reflecting reality

## Is this change user facing?
YES

## References (if applicable):
Closes #1351

### CODE REVIEW

File: cli/cli/commands/enclave/inspect/user_services.go [hunk 1]
```diff
@@ -49,8 +44,8 @@ func printUserServices(ctx context.Context, _ *kurtosis_context.KurtosisContext,
 			uuidToPrint = uuidStr
 		}
 
-		serviceStatus := userService.GetServiceStatus()
-		serviceStatusStr := service_status_stringifier.ServiceStatusStringifier(serviceStatus)
+		containerStatus := userService.GetContainer().GetStatus()
```
Comment (tedim52) [inline cli/cli/commands/enclave/inspect/user_services.go:47]: nice. If our notion of service status is 1:1 with the underlying container engine - i wonder if we really even need our own `ServiceStatus`.

**Review by tedim52 — APPROVED** [review]
LGTM

File: cli/cli/commands/enclave/inspect/user_services.go (hunk 1 above)
Comment (h4ck3rk3y) [reply cli/cli/commands/enclave/inspect/user_services.go:47]: Yeah, I think our own service status can be useful in a management UI where 

Our ServiceStatus - is the intended state
ContainerStatus - is the real state
