### PR TITLE
fix: run_sh doesn't remove new lines from input

### LINKED ISSUE #1597: piping doesn't work for run_sh
### What's your CLI version?

0.84.9

### Description & steps to reproduce

`run = "cat /foo/bar.txt | tr -d '\n'"`

for a file that looks like

```
foo
```

still keeps the newline

### Desired behavior

the new line gets dropped due to the pipe

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

CLI: the Command Line Interface

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
## Description:
Earlier `cat foo.txt | tr -d '\n'` wouldn't work as it would run as `cat foo.txt | tr -d ' '`

### CODE REVIEW

File: core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go [hunk 1]
```diff
@@ -253,7 +252,6 @@ func getCommandToRun(builtin *RunShCapabilities) (string, error) {
 	if err != nil {
 		return "", stacktrace.Propagate(err, "An error occurred while replacing runtime values in run_sh")
 	}
-	commandWithNoNewLines := strings.ReplaceAll(maybeSubCommandWithRuntimeValues, newlineChar, " ")
```
Comment (h4ck3rk3y) [inline core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go:256]: i don't know why we did this though?

Comment (h4ck3rk3y) [reply core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go:256]: ah we have a failing test for this

Comment (h4ck3rk3y) [reply core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go:256]: My theory is that while writing the tests someone saw that `echo kurtosis` would echo

```
kurtosis

```

and that messed up the first test so they changed it to remove new lines

Comment (h4ck3rk3y) [reply core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go:256]: @leoporoli fysa

**Review by leoporoli — APPROVED** [review]

File: core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go (hunk 1 above)
Comment (leoporoli) [reply core/server/api_container/server/startosis_engine/kurtosis_instruction/tasks/run_sh.go:256]: @h4ck3rk3y you conclusion makes sense
