### PR TITLE
fix: warn if engine version is greater than cli and error if cli > engine

### LINKED ISSUE #244: [bug]: explore erroring if the cli version > engine version
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.68.12

### (Optional) What is your metrics user ID?

_No response_

### What is the severity of this bug?

Papercut, this bug is frustrating, but I have a workaround.

### Description & steps to reproduce

https://kurtosistech.slack.com/archives/C04B5FXNKU4/p1679056457822239

### Relevant log output

_No response_

### Desired behavior

Figure out whether the current behavior is okay or error away and exit

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
## Description:
We would log with debug if engine > cli but people couldn't see it; caused confusion

## Is this change user facing?

* [x] Yes
* [ ] No

## References (if applicable):
(https://kurtosistech.slack.com/archives/C04B5FXNKU4/p1679056232033679)

### CODE REVIEW

File: cli/cli/helpers/engine_manager/engine_existence_guarantor.go [hunk 1]
```diff
@@ -224,7 +224,7 @@ func (guarantor *engineExistenceGuarantor) VisitRunning() error {
 			engineRestartCmd,
 		)
 	} else {
-		logrus.Debugf("Currently running engine version '%v' is >= the version the CLI expects", guarantor.maybeCurrentlyRunningEngineVersionTag)
+		logrus.Warningf("Currently running engine version '%v' is >= the version the CLI expects", guarantor.maybeCurrentlyRunningEngineVersionTag)
```
Comment (mieubrisse) [inline cli/cli/helpers/engine_manager/engine_existence_guarantor.go]: @h4ck3rk3y this is now going to go out to users, so can we make it more user-friendly (e.g. making it a complete sentence; giving them information on how to resolve)

**Review by mieubrisse — APPROVED** [review]

File: cli/cli/helpers/engine_manager/engine_existence_guarantor.go (hunk 1 above)
Comment (h4ck3rk3y) [reply cli/cli/helpers/engine_manager/engine_existence_guarantor.go]: Ha also saw that this condition would run if the versions are equal as well. Have put in a fix.
