### PR TITLE
fix: Only forward APIC port on remote context.

### LINKED ISSUE #1039: The CLI should not try to forward the APIC port when on local context
### What's your CLI version?

0.80.23

### Description & steps to reproduce

I ran the following sequence of events. AFAICT, `context switch` to a Kloud context started the Portal, but then when I switched back to the `default` context the Portal wasn't stopped which led to a broken `default` context.
```
 17:08:33 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context ls
    UUID           Name                Remote Host
*   e5605959c984   default             -
    37726bbf2de2   kurtosis-kloud-01   18.205.223.95
    78c04fa009f1   qcon-kloud          54.84.145.76
 17:08:35 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis con
config   (Manage configurations)     context  (Manage Kurtosis contexts)
 17:08:35 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context switch kurtosis-kloud-01
INFO[2023-08-01T17:08:43-03:00] Switching context...
INFO[2023-08-01T17:08:43-03:00] Prior to switching context, stop the local engine by running kurtosis engine stop
 17:08:43 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis engine stop
INFO[2023-08-01T17:08:48-03:00] Stopping Kurtosis engine...
INFO[2023-08-01T17:08:58-03:00] Kurtosis engine successfully stopped
 17:08:58 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context switch kurtosis-kloud-01
INFO[2023-08-01T17:13:23-03:00] Switching context...
Error:  An error occurred running command 'switch'
  Caused by: Error switching Kurtosis portal context
  Caused by: rpc error: code = Unknown desc = Unable to build client to remote portal server
  Caused by: Unable to connect to remote portal server
  Caused by: Portal server for this context unreachable at '18.205.223.95:9720'
  Caused by: Unable to reach Portal Server for this context after 5 retries
  Caused by: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 18.205.223.95:9720: i/o timeout"
 17:14:26 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis con
config   (Manage configurations)     context  (Manage Kurtosis contexts)
 17:14:26 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context rm  kurtosis-kloud-01
INFO[2023-08-01T17:15:34-03:00] Removing contexts...
INFO[2023-08-01T17:15:34-03:00] Contexts successfully removed
 17:15:34 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context ls
    UUID           Name         Remote Host
*   e5605959c984   default      -
    78c04fa009f1   qcon-kloud   54.84.145.76
 17:15:37 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context rm qcon-kloud
INFO[2023-08-01T17:15:43-03:00] Removing contexts...
INFO[2023-08-01T17:15:43-03:00] Contexts successfully removed
 17:15:43 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ls
README.md    compose.yaml
 17:15:44 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ls
README.md    compose.yaml
 17:15:47 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis ^C
 17:15:48 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ls
README.md    compose.yaml
 17:15:49 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis service logs ^C
 17:17:38 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ^Calthdraft
 17:17:41 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ls
README.md    compose.yaml
 17:17:41 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis con
config   (Manage configurations)     context  (Manage Kurtosis contexts)
 17:17:41 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context ls
    UUID           Name      Remote Host
*   e5605959c984   default   -
 17:17:44 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ls
README.md    compose.yaml
 17:17:45 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis import compose.yaml
INFO[2023-08-01T17:17:48-03:00] No Kurtosis engine was found; attempting to start one...
INFO[2023-08-01T17:17:50-03:00] Successfully started Kurtosis engine
INFO[2023-08-01T17:17:50-03:00] Enviroment loaded: map[PGADMIN_MAIL:your@email.com PGADMIN_PW:changeit POSTGRES_DB:postgres POSTGRES_PW:changeit POSTGRES_USER:yourUser]
Error:  An error occurred running command 'import'
  Caused by: An error occurred calling the run function for command 'import'
  Caused by: Couldn't create enclave
  Caused by: An error occurred creating an enclave ''
  Caused by: An error occurred creating an enclave context from a newly-created enclave; this should never happen
  Caused by: Unable to forward remote API container port to the local machine
  Caused by: rpc error: code = Unknown desc = Not connected to any environment at the moment. Connect to an environment first calling the 'ConnectToEnvironment' endpoint
 17:17:51 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context switch default
INFO[2023-08-01T17:20:08-03:00] Switching context...
INFO[2023-08-01T17:20:08-03:00] Prior to switching context, stop the local engine by running kurtosis engine stop
 17:20:08 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  ^Crtosis context ls
 17:20:16 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis import compose.yaml
INFO[2023-08-01T17:20:18-03:00] Enviroment loaded: map[PGADMIN_MAIL:your@email.com PGADMIN_PW:changeit POSTGRES_DB:postgres POSTGRES_PW:changeit POSTGRES_USER:yourUser]
Error:  An error occurred running command 'import'
  Caused by: An error occurred calling the run function for command 'import'
  Caused by: Couldn't create enclave
  Caused by: An error occurred creating an enclave ''
  Caused by: An error occurred creating an enclave context from a newly-created enclave; this should never happen
  Caused by: Unable to forward remote API container port to the local machine
  Caused by: rpc error: code = Unknown desc = Not connected to any environment at the moment. Connect to an environment first calling the 'ConnectToEnvironment' endpoint
 17:20:20 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis engine stop
INFO[2023-08-01T17:20:38-03:00] Stopping Kurtosis engine...
INFO[2023-08-01T17:20:48-03:00] Kurtosis engine successfully stopped
 17:20:48 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis context switch default
INFO[2023-08-01T17:20:52-03:00] Switching context...
INFO[2023-08-01T17:20:52-03:00] Already on context 'default'
 17:20:52 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis import compose.yaml
INFO[2023-08-01T17:20:54-03:00] No Kurtosis engine was found; attempting to start one...
INFO[2023-08-01T17:20:56-03:00] Successfully started Kurtosis engine
INFO[2023-08-01T17:20:56-03:00] Enviroment loaded: map[PGADMIN_MAIL:your@email.com PGADMIN_PW:changeit POSTGRES_DB:postgres POSTGRES_PW:changeit POSTGRES_USER:yourUser]
Error:  An error occurred running command 'import'
  Caused by: An error occurred calling the run function for command 'import'
  Caused by: Couldn't create enclave
  Caused by: An error occurred creating an enclave ''
  Caused by: An error occurred creating an enclave context from a newly-created enclave; this should never happen
  Caused by: Unable to forward remote API container port to the local machine
  Caused by: rpc error: code = Unknown desc = Not connected to any environment at the moment. Connect to an environment first calling the 'ConnectToEnvironment' endpoint
 17:20:58 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis portal stop
INFO[2023-08-01T17:21:37-03:00] Stopping the Kurtosis Portal
INFO[2023-08-01T17:21:37-03:00] Kurtosis Portal stopped
 17:21:37 /Users/argos/code/awesome-compose/postgresql-pgadmin (master)  kurtosis import compose.yaml
INFO[2023-08-01T17:21:40-03:00] Enviroment loaded: map[PGADMIN_MAIL:your@email.com PGADMIN_PW:changeit POSTGRES_DB:postgres POSTGRES_PW:changeit POSTGRES_USER:yourUser]
INFO[2023-08-01T17:21:54-03:00] Enclave was built with following output:
Service 'postgres' added with service UUID '50d8c5f0bd324c58bb392e01512da846'
Service 'pgadmin' added with service UUID 'd9331ba63b4040099659d66bcb821baf'
Name:            empty-volcano
UUID:            68447d9f8616
Status:          RUNNING
Creation Time:   Tue, 01 Aug 2023 17:21:40 -03

========================================= Files Artifacts =========================================
UUID   Name

========================================== User Services ==========================================
UUID           Name       Ports                                      Status
d9331ba63b40   pgadmin    docker-5050: 80/tcp -> 127.0.0.1:51983     RUNNING
50d8c5f0bd32   postgres   docker-5432: 5432/tcp -> 127.0.0.1:51981   RUNNING
```

### Desired behavior

I don't need to think about the Portal at all

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### PR DESCRIPTION
**Pull request by laurentluce**
## Description:
The CLI tried to forward the APIC port on local context.  This change makes sure that this happens only on remote context.

## Is this change user facing?
NO

## References (if applicable):
Closes #1039

### CODE REVIEW

File: api/golang/engine/lib/kurtosis_context/kurtosis_context.go [hunk 1]
```diff
@@ -347,13 +349,18 @@ func newEnclaveContextFromEnclaveInfo(
...
+		// for remote contexts, we need to tunnel the APIC port to the local machine
+		if store.IsRemote(currentContext) && portalClient != nil {
+			apicGrpcPort := enclaveInfo.GetApiContainerHostMachineInfo().GetGrpcPortOnHostMachine()
+			forwardApicPortArgs := portal_constructors.NewForwardPortArgs(apicGrpcPort, apicGrpcPort, &apicPortTransportProtocol)
+			if _, err := portalClient.ForwardPort(ctx, forwardApicPortArgs); err != nil {
+				return nil, stacktrace.Propagate(err, "Unable to forward remote API container port to the local machine")
+			}
 		}
+	} else {
+		logrus.Warnf("Unable to retrieve current Kurtosis context. This is not critical, it will assume using Kurtosis default context for now.")
```
Comment (gbouv) [inline api/golang/engine/lib/kurtosis_context/kurtosis_context.go:363]: I'd say we should throw here. Assuming default context if it's not can lead to unclear and confusing errors with the portal and stuffs. In the vein of failing early, we should prob throw

**Review by gbouv — APPROVED** [review]
with one suggestion

File: api/golang/engine/lib/kurtosis_context/kurtosis_context.go (hunk 1 above)
Comment (laurentluce) [reply api/golang/engine/lib/kurtosis_context/kurtosis_context.go:363]: There are multiple places like this one in the code so will address those in a separate PR after doing more research to make sure it won't break anything.
