### PR TITLE
fix: Enable autocomplete for the `files upload` path argument

### LINKED ISSUE #254: [bug]: The `path` element of `kurtosis files upload` doesn't tab-complete files
### What version of the Kurtosis CLI were you running when you encountered this bug?

0.68.10

### (Optional) What is your metrics user ID?

0497e811755b8f775ef0d99cd22b1ef221708b5a95119857a310cbc4f2eabcae

### What is the severity of this bug?

Papercut, this bug is frustrating, but I have a workaround.

### Description & steps to reproduce

Enter `kurtosis files upload SOME_ENCLAVE` and try to tab-complete the path. Nothing happens.

### Relevant log output

_No response_

### Desired behavior

Tab-completion of the path variable works

### PR DESCRIPTION
**Pull request by laurentluce**
## Description:
Make the `files upload` path arg a `NewFilepathOrDirpathArg` instance to support autocomplete in addition to validation.

## Is this change user facing?
NO

## References (if applicable):
Closes #254 
The remaining commands will be addressed in #601

### CODE REVIEW

File: cli/cli/commands/files/upload/upload.go [hunk 1]
```diff
@@ -51,10 +52,11 @@ var FilesUploadCmd = &engine_consuming_kurtosis_command.EngineConsumingKurtosisC
...
 			isEnclaveIdArgGreedy,
 		),
-		{
-			Key:            pathArgKey,
-			ValidationFunc: validatePathArg,
-		},
+		file_system_path_arg.NewFilepathOrDirpathArg(
+			pathArgKey,
+			isPathArgOptional,
+			nil,
```
Comment (mieubrisse) [inline cli/cli/commands/files/upload/upload.go]: can we swap the `nil` magic constant for a named constant per https://github.com/kurtosis-tech/kurtosis-internal-docs/blob/main/general-style-guide.md#replace-magic-constants-with-constants-named-for-their-purpose-not-their-value so it's clear what the arg is?

File: cli/cli/commands/files/upload/upload.go [hunk 2]
```diff
@@ -97,15 +99,3 @@ func run(
 	logrus.Infof("Files package '%v' uploaded with UUID: %v", fileArtifactName, filesArtifactUuid)
 	return nil
 }
-
-func validatePathArg(_ context.Context, _ *flags.ParsedFlags, args *args.ParsedArgs) error {
```
Comment (mieubrisse) [inline cli/cli/commands/files/upload/upload.go:101]: Are we removing this because the filepath arg already does this?

File: docs/docs/cli-reference/files-upload.md [hunk 3]
```diff
@@ -7,8 +7,11 @@ slug: /files-upload
 Files can be stored as a [files artifact][files-artifacts] inside an enclave by uploading them:
 
 ```bash
-kurtosis files upload $PATH_TO_FILES
+kurtosis files upload $THE_ENCLAVE_IDENTIFIER $PATH_TO_FILES
```
Comment (mieubrisse) [inline docs/docs/cli-reference/files-upload.md:10]: niceeeee

**Review by mieubrisse — APPROVED** [review]
approved pending comments

File: cli/cli/commands/files/upload/upload.go (hunk 2 above)
Comment (laurentluce) [reply cli/cli/commands/files/upload/upload.go:101]: > Are we removing this because the filepath arg already does this?

Yes

File: cli/cli/commands/files/upload/upload.go (hunk 1 above)
Comment (laurentluce) [reply cli/cli/commands/files/upload/upload.go]: I added a function set to nil to be used for this use case.  @mieubrisse Let me know if that works.
