### PR TITLE
fix: image download mode always applies to k8s as well

### LINKED ISSUE #2246: --image-download always doesn't work on k8s
### What's your CLI version?

0.87.3

### Description & steps to reproduce

If I use k8s as the backend for my kurtosis run, image-download always will be ignored, and the old images will be used.

### Desired behavior

If I set `--image-download always` flag, the pod image pull policy should be set to `Always` instead of `IfNotPresent`

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

CLI: the Command Line Interface

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
Earlier this flag was limited to Docker but now it works on k8s too

Closes #2246 

Earlier `latest` defaulted to `Always` but now it will depend on the flag sent 

https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2764-L2771

### CODE REVIEW

File: container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/user_services_functions/start_user_services.go [hunk 1]
```diff
@@ -3,6 +3,7 @@ package user_services_functions
 import (
 	"context"
 	"fmt"
+	"github.com/kurtosis-tech/kurtosis/container-engine-lib/lib/backend_interface/objects/image_download_mode"
```
Comment (leoporoli) [inline container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/user_services_functions/start_user_services.go:6]: will you add the docs in another PR?

**Review by leoporoli — APPROVED** [review]

File: container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/user_services_functions/start_user_services.go (hunk 1 above)
Comment (h4ck3rk3y) [reply container-engine-lib/lib/backend_impls/kubernetes/kubernetes_kurtosis_backend/user_services_functions/start_user_services.go:6]: Its already in docs :-)
