### PR TITLE
fix: args were positioned incorrectly

### LINKED ISSUE #1789: Cloud: custom configuration doesn't spin up required config
### What's your CLI version?

N/A

### Description & steps to reproduce

When I specify a custom config on kurtosis cloud, I still seem to get the default config. 

e.g: I have used this config:
```json
{
  "participants": [
    {
      "el_client_type": "geth",
      "cl_client_type": "lighthouse"
    },
    {
      "el_client_type": "besu",
      "cl_client_type": "prysm"
    }
  ],
  "network_params": {
    "deneb_fork_epoch": 1,
    "seconds_per_slot": 9
  },
  "additional_services": [
    "el_forkmon",
    "dora",
    "prometheus_grafana"
  ],
  "mev_type": null
}
```

See screenshot below:

Screenshot 2023-11-15 at 02 17 46
Screenshot 2023-11-15 at 02 17 39

uuid: 66a897a354f1

### Desired behavior

I should see
 
participants:
  - el_client_type: geth
    cl_client_type: lighthouse
  - el_client_type: besu
    cl_client_type: prysm

(Also I should be able to use yaml, but thats another issue already https://github.com/kurtosis-tech/kurtosis/issues/1785)

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Frontend: the Graphical User Interface, including the Enclave Manager

### PR DESCRIPTION
**Pull request by adschwartz**
## Description:
@barnabasbusa submitted an [issue](https://github.com/kurtosis-tech/kurtosis/issues/1789) that demonstrated that once run, the package would not apply the settings provided in the package `args`. I identified a bug that meant that while we were submitting the data it was in the wrong position and needed to be moved up on level (destructured).

In this PR we are also setting the JSON type as the default arg type.

## Is this change user facing?
YES

## References (if applicable):
Closes https://github.com/kurtosis-tech/kurtosis/issues/1789

### CODE REVIEW

File: enclave-manager/web/src/components/enclaves/modals/ConfigureEnclaveModal.tsx [hunk 1]
```diff
@@ -155,6 +159,20 @@ export const ConfigureEnclaveModal = ({
...
 
+    try {
+      console.debug("formData", formData);
+      if (formData.args && formData.args.args) {
+        formData.args.args = JSON.parse(formData.args.args);
+        console.debug("successfully parsed args as proper JSON", formData.args.args);
+      }
+    } catch (err) {
+      toast({
+        title: `An error occurred while preparing data for running package. The package arguments were not proper JSON: ${stringifyError("asdas")}`,
```
Comment (leoporoli) [inline enclave-manager/web/src/components/enclaves/modals/ConfigureEnclaveModal.tsx]: I think the argument for the stringifyError is wrong, it should be stringifyError(err) I think

**Review by leoporoli — APPROVED** [review]

File: enclave-manager/web/src/components/enclaves/modals/ConfigureEnclaveModal.tsx (hunk 1 above)
Comment (adschwartz) [reply enclave-manager/web/src/components/enclaves/modals/ConfigureEnclaveModal.tsx]: oh good catch. Fixing!
