### PR TITLE
fix: remove historical enclave names from auto complete

### LINKED ISSUE #1045: Autocomplete for `kurtosis service logs` returns already deleted enclaves
### What's your CLI version?

0.80.23

### Description & steps to reproduce

`kurtosis service logs <TAB>`
returns:
```
blue-steppe          dreaming-crag        rustling-peak        spooky-oasis         winter-ocean
delicate-wilderness  muddy-canyon         smooth-estuary       timid-coast          wispy-trail
```

`kurtosis enclave ls`
returns: 
```
UUID           Name          Status     Creation Time
6d21d7b328bf   blue-steppe   RUNNING    Wed, 02 Aug 2023 16:57:02 CEST
```

### Desired behavior

`kurtosis service logs <TAB>` should tab complete only active, not stopped/removed enclaves. 

### What is the severity of this bug?

Papercut; this bug is frustrating, but I have a workaround.

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
## Description:
We used to populate historical enclave names and service names in auto complete but that was confusing to me and Barnabas.

### CODE REVIEW

File: cli/cli/commands/service/logs/logs.go [hunk 1]
```diff
@@ -105,17 +105,16 @@ var ServiceLogsCmd = &engine_consuming_kurtosis_command.EngineConsumingKurtosisC
 	Args: []*args.ArgConfig{
 		//TODO disabling enclaveID validation and serviceUUID validation for allowing consuming logs from removed or stopped enclaves
 		//TODO we should enable them when #879 is ready: https://github.com/kurtosis-tech/kurtosis/issues/879
-		enclave_id_arg.NewHistoricalEnclaveIdentifiersArgWithValidationDisabled(
+		enclave_id_arg.NewEnclaveIdentifierArg(
```
Comment (h4ck3rk3y) [inline cli/cli/commands/service/logs/logs.go:108]: this can be added back when we add centralized logs components

**Review by leoporoli — APPROVED** [review]
