### PR TITLE
fix:  made forwarding efficient by reducing calls to Kubernetes

### LINKED ISSUE #1075: Service ports forward connection initialization is slow with a large number of services
### What's your CLI version?

0.81.4

### Description & steps to reproduce

The Gateway takes a long time to initialize the service port forward connections when there are many services.  Two backend calls are made to build each connection.

### Desired behavior

The Gateway should initialize the service port forward connections with no calls to the backend. The port forward URL has a well-known format and it can be built directly since we know how the namespace and pod are derived from the enclave and service info.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
This PR needs some work. This has been created for a visual diff

### CODE REVIEW

File: cli/cli/kurtosis_gateway/connection/provider.go [hunk 1]
```diff
@@ -211,7 +182,14 @@ func (provider *GatewayConnectionProvider) getRunningPodNamesByLabels(namespace
 	return runningPodNames, nil
 }
 
+// TODO - this function shouldn't exist when kt- + enclave name is the namespace inside kurtosis
+// https://github.com/kurtosis-tech/kurtosis/issues/1203 - till then we cache it
 func (provider *GatewayConnectionProvider) getEnclaveNamespaceNameForEnclaveId(enclaveId string) (string, error) {
+	enclaveNamespaceName, found := provider.enclaveIdToEnclaveNamespaceName[enclaveId]
```
Comment (laurentluce) [inline cli/cli/kurtosis_gateway/connection/provider.go:188]: Great workaround until the namespace names are deterministic.

**Review by laurentluce — APPROVED** [review]
Thanks @h4ck3rk3y !

File: cli/cli/kurtosis_gateway/connection/provider.go (hunk 1 above)
Comment (h4ck3rk3y) [reply cli/cli/kurtosis_gateway/connection/provider.go:188]: Thank you! :-)
