### PR TITLE
fix: truncate output if greater than 64*1024 characters

### LINKED ISSUE #1019: kurtosis run breaks if the server returns more than 4mb of data
### What's your CLI version?

0.80.12

### Description & steps to reproduce

def run(plan):
    plan.run_python(
        run = """
print("hello world"*2**20)
"""
    )

If you run the above you will get the error. Barnabas ran into this.

### Desired behavior

Kurtosis shouldn't break.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
## Description:
We would written a lot of data and the client would fail as it wouldn't accept over > 4mb.

going with this limit instead of something lower as a lot of our tests rely on output value matching.

### CODE REVIEW

File: core/server/api_container/server/startosis_engine/startosis_executor.go [hunk 1]
```diff
@@ -15,6 +16,10 @@ import (
 const (
 	progressMsg      = "Execution in progress"
 	ParallelismParam = "PARALLELISM"
+	// we limit the output to 600 characters
+	// TODO(tedi) get rid of this in favor of streaming
```
Comment (tedim52) [inline core/server/api_container/server/startosis_engine/startosis_executor.go:20]: been wanting my name in the codebase, thanks gyani

**Review by tedim52 — APPROVED** [review]
LGTM
